language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  pip install -r requirements.txt;
script:
  - nosetests -vv
  - python -m hashit test/support/example.bin
notifications:
  email:
    - depostorivo@gmail.com
