language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  pip install -r requirements.txt;
script:
  - nosetests -vv
  - python -m hashit test/support/example.bin
  - python -m hashit test/support/example.bin --hash-type CRC16
  - python -m hashit test/support/example.bin --hash-type CRC32
  - python -m hashit test/support/example.bin --hash-type MD5
  - python -m hashit test/support/example.bin --hash-type SH1
  - python -m hashit test/support/example.bin --hash-type SH224
  - python -m hashit test/support/example.bin --hash-type SH256
notifications:
  email:
    - depostorivo@gmail.com
